### ISSUE TITLE
elf2flt: libbfd API issue with binutils-2.34+

### ISSUE THREAD

**Issue by RomainNaour** [uclinux-dev/elf2flt#14]
Hi,

The latest Binutils release (2.34) is not compatible with elf2flt due to a change in  bfd_section_* macros.

The issue has been reported to the Binutils mailing list but Alan Modra recommend to bundle libbfd library sources into each projects using it. That's because the API is not stable over the time without any backward compatibility guaranties.

See: https://sourceware.org/ml/binutils/2020-02/msg00044.html

Best regards,
Romain

**Comment by vapier** [comment]
we don't bundle bfd, and we're not going to start.  it simply doesn't work for our integration model (where people are using random forked copies of binutils to support their arch/target).

we'll need to have the code detect the version and adjust API usage based on it.

**Comment by RomainNaour** [comment]
Hello,

I sent a PR to check the libbfd API.

Best regards,
Romain

**Comment by gregungerer** [comment]
Fixed. Romain Naour's patch applied.
