### ISSUE TITLE
 Input file contains no relocation info error

### ISSUE THREAD

**Issue by mahyar1284** [uclinux-dev/elf2flt#21]
I have a simple c helloworld app:
```
#include <stdio.h>

int main() {
   printf("Hello World!");
   return 0;
}
```
and I've compiled it on ubuntu 20 using prebuilt arm toolchain:
```
$arm-linux-gnueabi-gcc -shared -fPIE -fPIC -mcpu=cortex-m3 helloworld.c -o out.o
```
that should create a FD-PIC elf. then I execute elf2flt:
```
$elf2flt out.o
    elf2flt: out.o: Input file contains no relocation info
```
what's wrong here?

**Comment by mahyar1284** [comment]
even I tried to compile it as a relocatable elf `-c helloworld.c` but it was useless. I got another error.
```
elf2flt: ERROR: text=0x18 overlaps data=0x0 ?
```

**Comment by vapier** [comment]
you cannot convert a partially linked object as produced by `-c` to a FLT executable, so that failing is to be expected.

you should be integrating these tools into the toolchain directly and then linking with `-elf2flt`, not running tools directly yourself.  please reconfigure your toolchain accordingly.

**Comment by mahyar1284** [comment]
I built 2 toolchain (with elf2flt enabled in menuconfig) one with crosstool-ng and one with buildroot but both of them throws an error:
```
$ ../buildroot/output/host/bin/arm-linux-gcc -elf2flt helloworld.c -o out.o
/home/mahyar1284/embedded/buildroot/output/host/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: warning: cannot find entry symbol lf2flt; defaulting to 0000000000000000
```
```
$ ../../x-tools/arm-linux-uclibcgnueabi/bin/arm-linux-uclibcgnueabi-gcc -elf2flt helloworld.c -o out.o
/home/mahyar1284/x-tools/arm-linux-uclibcgnueabi/arm-linux-uclibcgnueabi/bin/ld.real: warning: cannot find entry symbol lf2flt; defaulting to 00000000000100e0
```

**Comment by vapier** [comment]
if you're seeing those errors, then elf2flt isn't integrated correctly.  you'll want to talk to the projects who created the toolchains.

```
$ echo 'main(){}' > test.c
$ bfin-uclinux-gcc test.c -elf2flt
$ file a.out*
a.out:     BFLT executable - version 4 ram
a.out.gdb: ELF 32-bit LSB executable, Analog Devices Blackfin, version 1 (SYSV), statically linked, with debug_info, not stripped
```

you can also try `-Wl,-elf2flt` instead of `-elf2flt`, but i'm guessing that doesn't work either.
```
$ bfin-uclinux-gcc test.c -Wl,-elf2flt=-v
TEXT -> vma=0x0 len=0x580
DATA -> vma=0x580 len=0x60
BSS  -> vma=0x5e0 len=0x40
SECTION: .text [0x1505628]: flags=0x11f vma=0x0
 RELOCS: .text [0x1505628]: flags=0x11f vma=0x0
  RELOC[0]: offset=0x56c symbol=.text+0x0 section=.text size=22028960 fixup=0x0 (reloc=0x56c)
...
```

**Comment by vapier** [comment]
also, i think only `*-uclinux-*` toolchains tend to support elf2flt.  `*-linux-*` toolchains target MMU systems.  you seem to be using `arm-linux-*` everywhere.

**Comment by mahyar1284** [comment]
> also, i think only `*-uclinux-*` toolchains tend to support elf2flt. `*-linux-*` toolchains target MMU systems. you seem to be using `arm-linux-*` everywhere.

first of, thank you so much for guiding me. it's many years that uclinux development has stoped as I know. and new releases of official mainline kernel officialy supports no-mmu targets such as cortex m3, m4 and m7 and ... and I'm not using uclinux on my board. I'm using linux kernel 5.12 with initial stm32_defconfig configuration. 

---
> you can also try -Wl,-elf2flt instead of -elf2flt, but i'm guessing that doesn't work either.

I tried to use -Wl,-elf2flt instead of -elf2flt, and it worked well :) and produced flat binary. but when I check the format it's different from what your binaries are.
```
$ file out.o
      out.o: BFLT executable - version 4 gotpic
```
but yours is `version 4 ram` instead of `version 4 gotpic`
and when I try to run it on qemu it throws this error:
```
qemu-arm -cpu cortex-m4 out.o
      BINFMT_FLAT: reloc outside program 0x7fff9670 (0 - 0xffffda58/0x9258)
      Aborted
```
what's the problem?

**Comment by vapier** [comment]
i wouldn't worry about gotpic-vs-ram.  each arch might have diff defaults or requirements there.

wrt qemu, it's been broken for as long as i've worked on it which has prob been about 10 years now.  i had some local changes to make it work, but it's been a while since i last poked it.  using FDPIC ELF was easier.

i would test it on real hardware instead.

**Comment by mahyar1284** [comment]
I don't have much info about FDPIC-ELFs. does this produce an fdpic-elf? `arm-linux-gnueabi-gcc helloworld.c -mcpu=cortex-m4 -Wl,-fdpic -fpie -fPIE -fPIC -shared -o out.o`. 
Is it just a normal elf that is dynamic (ET_DYN) and position independent (PIC and PIE)?
```
$ arm-linux-gnueabi-objdump -fR out.o



out.o:     file format elf32-littlearm
architecture: armv7e-m, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000308

DYNAMIC RELOCATION RECORDS
OFFSET   TYPE              VALUE
00010f10 R_ARM_RELATIVE    *ABS*
00010f14 R_ARM_RELATIVE    *ABS*
00011028 R_ARM_RELATIVE    *ABS*
00011018 R_ARM_GLOB_DAT    __cxa_finalize@GLIBC_2.4
0001101c R_ARM_GLOB_DAT    _ITM_deregisterTMCloneTable
00011020 R_ARM_GLOB_DAT    __gmon_start__
00011024 R_ARM_GLOB_DAT    _ITM_registerTMCloneTable
e7fdf000 R_ARM_JUMP_SLOT   __cxa_finalize@GLIBC_2.4
00011010 R_ARM_JUMP_SLOT   puts@GLIBC_2.4
00011014 R_ARM_JUMP_SLOT   __gmon_start__
```
I don't have a real hardware for now. can u please do me a favor and test it for me? 
[out.ZIP](https://github.com/uclinux-dev/elf2flt/files/7020719/out.ZIP)
