### ISSUE TITLE
Failed BINFMT_FLAT with uclinux tools-20030909

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [uclinux-dev/elf2flt#33]
I'm compiling sash for an armnommu target. However, when i'm running it on the target, I got this error:
```
BINFMT_FLAT: bad magic/rev (0x0, need 0x4)
```
Does anyone know how to fix?

P.S. The flthdr output:
```
romfs/bin/sh                                                                                          Magic:        bFLT                                                                                Rev:          4                                                                                   Build Date:   Fri Dec 22 17:40:51 2023                                                            Entry:        0x50                                                                                Data Start:   0xc120                                                                              Data End:     0xd6a0                                                                              BSS End:      0xe450                                                                              Stack Size:   0x1000                                                                              Reloc Start:  0xd6a0
    Reloc Count:  0x322                                                                               Flags:        0x1 ( Load-to-Ram )
```
I have tried it with qemu-arm, but got the same error.

**Comment by wbx-github** [comment]
Hi,
can you share more details. Which version of elf2flt, binutils, gcc and Linux kernel are you using.
For me it works fine. I am using OpenADK (https://openadk.org) to compile everything from scratch.
I am tested on Qemu ARM with versatile-pb emulation and Linux 6.1.69.
best regards
 Waldemar

**Comment by fish4terrisa-MSDSM** [comment]
I was using the uclinux tools-20030909 built by myself. However, after changed to use the prebuilt toolchain, this error was fixed. It seems that these old toolchains are not compatible with the recent gcc (for exmaple, the gcc toolchain from archlinux repo)

**Comment by vapier** [comment]
yeah, there's not really support for older versions.  if you want support, you need to use current versions.
